// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcwhuqnmmldgyzkodyae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indjd2h1cW5tbWxkZ3l6a29keWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzE3OTUsImV4cCI6MjA3MjY0Nzc5NX0.cFs_vyioCNw2XS4zhPw_y5MU2p9mZkvc0WMaJU3oblw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});